# ... NEW, CORRECT VERSION ...
service: compliance-analyzer-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  profile: hackathon-participant-144274058030
  httpApi:
    cors: true
  role: arn:aws:iam::144274058030:role/MyNgoComplianceLambdaRole

package:
  patterns:
    - '!ngo-compliance-ui/**'
    - '!node_modules/**'
    - '!.git/**'
    - '!.vscode/**'
    - '!*.md'
    - '!kaushikcrawl.py'
    - handler.py
    - requirements.txt

functions:
  analyze:
    handler: handler.analyze
    timeout: 30
    events:
      - httpApi:
          path: /analyze
          method: post
